### ISSUE TITLE
TypeError:'numpy.int32' object is not iterable when 'gym.make('HandReach-v0')'

### ISSUE THREAD

**Issue by LiDuan1111** [openai/mujoco-py#304] opened 2018-10-03 07:23 UTC

**Comment by chrisole** [comment] 2018-10-17 04:32
Have u resolve it?

**Comment by machinaut** [comment] 2018-10-17 22:39
@LiDuan1111 could you describe what situation the error occurred in, and provide more of the error message?

Closing for now, but reopen when there is more info.

**Closed by machinaut** 2018-10-17 22:39 UTC

**Comment by aaronsnoswell** [comment] 2019-01-29 02:12
Duplicate of #324.
